spring:
  application:
    name: module-api
  profiles:
    include:
      - api
      - domain
    group:
      local:
        - api-local
        - domain-local
      dev:
        - api-dev
        - domain-dev
      prod:
        - api-prod
        - domain-prod

management:
  endpoints:
    web:
      exposure:
        include: health